package:
  name: lyve-set
  version: "1.1.4"

about:
  home: https://github.com/jlumpe/lyve-set-conda
  license: MIT
  license_file: LICENSE

source:
  # Get all lksatz's repos from git
  git_url: https://github.com/jlumpe/lyve-SET.git
  git_rev: v1.1.4-head
#  - git_url: https://github.com/lskatz/Schedule--SGELK.git
#    folder: build/schedule
#  - git_url: https://github.com/lskatz/cg-pipeline
#    folder: lib/cg-pipeline

requirements:
  build:
    - cmake
    - git
    - wget
    - blast  # For install-phast step
  run:
    # Most of these are in the bioconda channel
    - vcftools >=0.1.14
    - varscan >=2.3.7
    - snpeff
    - samtools >=1.3.1
    - htslib >=1.3.2
    - bcftools >=1.3.1
    - smalt >=0.7.6
    - snap-aligner 1.0*  # Pre-release versioning not supported
    - raxml >=8.1.16
    - entrez-direct
    - blast
